### ISSUE TITLE
No current branch when updating

### ISSUE THREAD

**Issue by lfoscari** [jedavies-dev/kiss-aarch64#4]
Noob here, I'm installing KISS for the first time on a Raspberry Pi 4, when doing `kiss update` it stops with the following error
```
~ # kiss update
-> Updating repositories 
-> /root/repos/kiss-aarch64  
Already up to date.
Submodule path 'modules/community': checked out 'c130b2f086b7bd4c850e3d0aba21e4c446140f1a'
Submodule path 'modules/repo': checked out '83f125553f1d213e473390146436684505d910ff'
-> /root/repos/kiss-aarch64/modules/repo  
fatal: No current branch.
```
I tried running
```
~/repos/kiss-aarch64/modules/repo # git status
HEAD detached at 83f12555
nothing to commit, working tree clean
```
My `$KISS_PATH` is
```
/root/repos/kiss-aarch64/core:/root/repos/kiss-aarch64/overrides:/root/repos/kiss-aarch64/extra:/root/repos/kiss-aarch64/modules/repo/extra:/root/repos/kiss-aarch64/modules/repo/xorg
```

**Comment by jedavies-dev** [comment]
Hi lfoscari.

I wasn't able to recreate the issue. I did the following to test:

 - Download latest tarball
 - ``mkdir test-chroot``
 - ``sudo tar xf kiss-chroot-aarch64-2020.9-1.tar.xz -C kiss-aarch64-test/ --strip-components=1``
 - ``sudo kiss-chroot test-chroot/``
 - ``mkdir repos && cd repos``
 - ``git clone https://github.com/jedavies-dev/kiss-aarch64.git``
 - export KISS_PATH as you have in your comment
 - ``export KISS_SU=su``
 - ``kiss u``

This works OK for me.

Some questions:
 - Are you using the latest tarball?
 - Did you unzip the tarball using sudo or root?
 - Are you using kiss-chroot or just chroot or something else? Or is this running as your main OS?
 - Any other flags you have set?

Can you also try building as a normal user? This would normally be preferred rather than building packages as root.

**Comment by MarcusE1W** [comment]
So, I think it worked for me too. I write this a bit longish as it took me a while to get there:

download tarball from repro -> kiss-chroot-aarch64-2020.9-1.tar.xz then cd into the download folder and extract the tar-file

```
tar xf kiss-chroot-aarch64-2020.9-1.tar.xz
```

this gives the new folder `kiss-aarch64-testroot`

Start chroot
```
sudo ./kiss-aarch64-testroot/bin/kiss_chroot ./kiss-aarch64-testroot
```

make sure to be in the home folder `/root`
```
cd
```

Download the repro
```
mkdir repos && cd repos
git clone https://github.com/jedavies-dev/kiss-aarch64.git
```

export the `KISS_PATH`
```
export KISS_PATH=/root/repos/kiss-aarch64/core:/root/repos/kiss-aarch64/overrides:/root/repos/kiss-aarch64/extra:/root/repos/kiss-aarch64/modules/repo/extra:/root/repos/kiss-aarch64/modules/repo/xorg
```

export `KISS_SU`
```
export KISS_SU=su
```

export build flags as given for the tarball release:
```
export CFLAGS="-mcpu=generic -mtune=generic -Os -pipe"
export CXXFLAGS="-mcpu=generic -mtune=generic -Os -pipe"
export MAKEFLAGS="-j6"
```

start the kiss update
```
kiss u
```

In my case I got the mesaage to update the package manager first -> press `Enter`

After that start the update again
```
kiss u
```
In my case I was asked to agree to build some dependencies -> press `Enter` and wait... a lot. (~15 min in my case)

**Comment by jedavies-dev** [comment]
Closing since I could not recreate the issue, other user reported the same.
@lfoscari please post further details if you'd like me to look into this more.
